/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateTransactionDto } from "../create-transaction-dto.ts";

/**
 * @example [object Object]
 */
export type TransactionsControllerCreate201 = any;

/**
 * @description Categoria não encontrada
 */
export type TransactionsControllerCreate404 = any;

export type TransactionsControllerCreateMutationRequest = CreateTransactionDto;

export type TransactionsControllerCreateMutationResponse =
	TransactionsControllerCreate201;

export type TransactionsControllerCreateMutation = {
	Response: TransactionsControllerCreate201;
	Request: TransactionsControllerCreateMutationRequest;
	Errors: TransactionsControllerCreate404;
};
