/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionsControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @example [object Object]
 */
export type TransactionsControllerRemove200 = any;

export type TransactionsControllerRemoveMutationResponse =
	TransactionsControllerRemove200;

export type TransactionsControllerRemoveMutation = {
	Response: TransactionsControllerRemove200;
	PathParams: TransactionsControllerRemovePathParams;
	Errors: any;
};
