/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateTransactionDto } from "../update-transaction-dto.ts";

export type TransactionsControllerUpdatePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Transação atualizada
 */
export type TransactionsControllerUpdate200 = any;

/**
 * @description Transação ou categoria não encontrada
 */
export type TransactionsControllerUpdate404 = any;

export type TransactionsControllerUpdateMutationRequest = UpdateTransactionDto;

export type TransactionsControllerUpdateMutationResponse =
	TransactionsControllerUpdate200;

export type TransactionsControllerUpdateMutation = {
	Response: TransactionsControllerUpdate200;
	Request: TransactionsControllerUpdateMutationRequest;
	PathParams: TransactionsControllerUpdatePathParams;
	Errors: TransactionsControllerUpdate404;
};
