/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example 2026-03,2026-02
 */
export type TransactionsControllerListMonths200 = any;

export type TransactionsControllerListMonthsQueryResponse =
	TransactionsControllerListMonths200;

export type TransactionsControllerListMonthsQuery = {
	Response: TransactionsControllerListMonths200;
	Errors: any;
};
