/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionsControllerListQueryParams = {
	/**
	 * @description Formato YYYY-MM
	 * @type string | undefined
	 */
	month?: string;
};

/**
 * @example [object Object]
 */
export type TransactionsControllerList200 = any;

/**
 * @description Formato de mês inválido (YYYY-MM)
 */
export type TransactionsControllerList400 = any;

export type TransactionsControllerListQueryResponse =
	TransactionsControllerList200;

export type TransactionsControllerListQuery = {
	Response: TransactionsControllerList200;
	QueryParams: TransactionsControllerListQueryParams;
	Errors: TransactionsControllerList400;
};
