/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetsControllerListQueryParams = {
	/**
	 * @description Formato YYYY-MM
	 * @type string | undefined
	 */
	month?: string;
};

/**
 * @example
 */
export type BudgetsControllerList200 = any;

export type BudgetsControllerListQueryResponse = BudgetsControllerList200;

export type BudgetsControllerListQuery = {
	Response: BudgetsControllerList200;
	QueryParams: BudgetsControllerListQueryParams;
	Errors: any;
};
