/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetsControllerProgressPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Progresso do orçamento do mês
 */
export type BudgetsControllerProgress200 = any;

export type BudgetsControllerProgressQueryResponse =
	BudgetsControllerProgress200;

export type BudgetsControllerProgressQuery = {
	Response: BudgetsControllerProgress200;
	PathParams: BudgetsControllerProgressPathParams;
	Errors: any;
};
