/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateBudgetDto } from "../update-budget-dto.ts";

export type BudgetsControllerUpdatePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Orçamento atualizado
 */
export type BudgetsControllerUpdate200 = any;

export type BudgetsControllerUpdateMutationRequest = UpdateBudgetDto;

export type BudgetsControllerUpdateMutationResponse =
	BudgetsControllerUpdate200;

export type BudgetsControllerUpdateMutation = {
	Response: BudgetsControllerUpdate200;
	Request: BudgetsControllerUpdateMutationRequest;
	PathParams: BudgetsControllerUpdatePathParams;
	Errors: any;
};
