/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateBudgetDto } from "../create-budget-dto.ts";

/**
 * @description Orçamento criado com sucesso
 */
export type BudgetsControllerCreate201 = any;

/**
 * @description Categoria não encontrada
 */
export type BudgetsControllerCreate404 = any;

/**
 * @description Já existe um orçamento para essa categoria neste mês
 */
export type BudgetsControllerCreate409 = any;

export type BudgetsControllerCreateMutationRequest = CreateBudgetDto;

export type BudgetsControllerCreateMutationResponse =
	BudgetsControllerCreate201;

export type BudgetsControllerCreateMutation = {
	Response: BudgetsControllerCreate201;
	Request: BudgetsControllerCreateMutationRequest;
	Errors: BudgetsControllerCreate404 | BudgetsControllerCreate409;
};
