/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetsControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @example [object Object]
 */
export type BudgetsControllerRemove200 = any;

export type BudgetsControllerRemoveMutationResponse =
	BudgetsControllerRemove200;

export type BudgetsControllerRemoveMutation = {
	Response: BudgetsControllerRemove200;
	PathParams: BudgetsControllerRemovePathParams;
	Errors: any;
};
