/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	TransactionsControllerListQueryResponse,
	TransactionsControllerListQueryParams,
	TransactionsControllerList400,
} from "../schemas/transactions/transactions-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerListUrl() {
	const res = { method: "GET", url: `/v1/transactions` as const };
	return res;
}

/**
 * {@link /v1/transactions}
 */
export async function transactionsControllerList(
	params?: TransactionsControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionsControllerListQueryResponse,
		ResponseErrorConfig<TransactionsControllerList400>,
		unknown
	>({
		method: "GET",
		url: getTransactionsControllerListUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
