/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	TransactionsControllerGetByIdQueryResponse,
	TransactionsControllerGetByIdPathParams,
	TransactionsControllerGetById404,
} from "../schemas/transactions/transactions-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerGetByIdUrl(
	id: TransactionsControllerGetByIdPathParams["id"],
) {
	const res = { method: "GET", url: `/v1/transactions/${id}` as const };
	return res;
}

/**
 * {@link /v1/transactions/:id}
 */
export async function transactionsControllerGetById(
	id: TransactionsControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionsControllerGetByIdQueryResponse,
		ResponseErrorConfig<TransactionsControllerGetById404>,
		unknown
	>({
		method: "GET",
		url: getTransactionsControllerGetByIdUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
