/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	TransactionsControllerCreateMutationRequest,
	TransactionsControllerCreateMutationResponse,
	TransactionsControllerCreate404,
} from "../schemas/transactions/transactions-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerCreateUrl() {
	const res = { method: "POST", url: `/v1/transactions` as const };
	return res;
}

/**
 * {@link /v1/transactions}
 */
export async function transactionsControllerCreate(
	data: TransactionsControllerCreateMutationRequest,
	config: Partial<
		RequestConfig<TransactionsControllerCreateMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		TransactionsControllerCreateMutationResponse,
		ResponseErrorConfig<TransactionsControllerCreate404>,
		TransactionsControllerCreateMutationRequest
	>({
		method: "POST",
		url: getTransactionsControllerCreateUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
