/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { TransactionsControllerListMonthsQueryResponse } from "../schemas/transactions/transactions-controller-list-months.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerListMonthsUrl() {
	const res = { method: "GET", url: `/v1/transactions/months` as const };
	return res;
}

/**
 * {@link /v1/transactions/months}
 */
export async function transactionsControllerListMonths(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionsControllerListMonthsQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getTransactionsControllerListMonthsUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
