/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	TransactionsControllerRemoveMutationResponse,
	TransactionsControllerRemovePathParams,
} from "../schemas/transactions/transactions-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerRemoveUrl(
	id: TransactionsControllerRemovePathParams["id"],
) {
	const res = { method: "DELETE", url: `/v1/transactions/${id}` as const };
	return res;
}

/**
 * {@link /v1/transactions/:id}
 */
export async function transactionsControllerRemove(
	id: TransactionsControllerRemovePathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		TransactionsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getTransactionsControllerRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
