/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	TransactionsControllerUpdateMutationRequest,
	TransactionsControllerUpdateMutationResponse,
	TransactionsControllerUpdatePathParams,
	TransactionsControllerUpdate404,
} from "../schemas/transactions/transactions-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getTransactionsControllerUpdateUrl(
	id: TransactionsControllerUpdatePathParams["id"],
) {
	const res = { method: "PUT", url: `/v1/transactions/${id}` as const };
	return res;
}

/**
 * {@link /v1/transactions/:id}
 */
export async function transactionsControllerUpdate(
	id: TransactionsControllerUpdatePathParams["id"],
	data: TransactionsControllerUpdateMutationRequest,
	config: Partial<
		RequestConfig<TransactionsControllerUpdateMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		TransactionsControllerUpdateMutationResponse,
		ResponseErrorConfig<TransactionsControllerUpdate404>,
		TransactionsControllerUpdateMutationRequest
	>({
		method: "PUT",
		url: getTransactionsControllerUpdateUrl(id).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
