/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionsControllerListMonthsQueryResponse } from "../../schemas/transactions/transactions-controller-list-months.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { transactionsControllerListMonths } from "../transactions-controller-list-months.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const transactionsControllerListMonthsQueryKey = () =>
	[{ url: "/v1/transactions/months" }] as const;

export type TransactionsControllerListMonthsQueryKey = ReturnType<
	typeof transactionsControllerListMonthsQueryKey
>;

export function useTransactionsControllerListMonthsQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = transactionsControllerListMonthsQueryKey();
	return queryOptions<
		TransactionsControllerListMonthsQueryResponse,
		ResponseErrorConfig<Error>,
		TransactionsControllerListMonthsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return transactionsControllerListMonths({
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/transactions/months}
 */
export function useTransactionsControllerListMonths<
	TData = TransactionsControllerListMonthsQueryResponse,
	TQueryData = TransactionsControllerListMonthsQueryResponse,
	TQueryKey extends QueryKey = TransactionsControllerListMonthsQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				TransactionsControllerListMonthsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? transactionsControllerListMonthsQueryKey();

	const query = useQuery(
		{
			...useTransactionsControllerListMonthsQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
