/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	TransactionsControllerRemoveMutationResponse,
	TransactionsControllerRemovePathParams,
} from "../../schemas/transactions/transactions-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { transactionsControllerRemove } from "../transactions-controller-remove.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const transactionsControllerRemoveMutationKey = () =>
	[{ url: "/v1/transactions/:id" }] as const;

export type TransactionsControllerRemoveMutationKey = ReturnType<
	typeof transactionsControllerRemoveMutationKey
>;

export function useTransactionsControllerRemoveMutationOptions<
	TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const mutationKey = transactionsControllerRemoveMutationKey();
	return mutationOptions<
		TransactionsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: TransactionsControllerRemovePathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return transactionsControllerRemove(id, config);
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{ id: TransactionsControllerRemovePathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerRemoveMutationKey();

	const baseOptions = useTransactionsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: TransactionsControllerRemovePathParams["id"] },
		TContext
	>;

	return useMutation<
		TransactionsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: TransactionsControllerRemovePathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: TransactionsControllerRemovePathParams["id"] },
		TContext
	>;
}
