/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	TransactionsControllerCreateMutationRequest,
	TransactionsControllerCreateMutationResponse,
	TransactionsControllerCreate404,
} from "../../schemas/transactions/transactions-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { transactionsControllerCreate } from "../transactions-controller-create.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const transactionsControllerCreateMutationKey = () =>
	[{ url: "/v1/transactions" }] as const;

export type TransactionsControllerCreateMutationKey = ReturnType<
	typeof transactionsControllerCreateMutationKey
>;

export function useTransactionsControllerCreateMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<TransactionsControllerCreateMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = transactionsControllerCreateMutationKey();
	return mutationOptions<
		TransactionsControllerCreateMutationResponse,
		ResponseErrorConfig<TransactionsControllerCreate404>,
		{ data: TransactionsControllerCreateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return transactionsControllerCreate(data, config);
		},
	});
}

/**
 * {@link /v1/transactions}
 */
export function useTransactionsControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerCreateMutationResponse,
			ResponseErrorConfig<TransactionsControllerCreate404>,
			{ data: TransactionsControllerCreateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<TransactionsControllerCreateMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerCreateMutationKey();

	const baseOptions = useTransactionsControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerCreateMutationResponse,
		ResponseErrorConfig<TransactionsControllerCreate404>,
		{ data: TransactionsControllerCreateMutationRequest },
		TContext
	>;

	return useMutation<
		TransactionsControllerCreateMutationResponse,
		ResponseErrorConfig<TransactionsControllerCreate404>,
		{ data: TransactionsControllerCreateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerCreateMutationResponse,
		ResponseErrorConfig<TransactionsControllerCreate404>,
		{ data: TransactionsControllerCreateMutationRequest },
		TContext
	>;
}
