/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	TransactionsControllerUpdateMutationRequest,
	TransactionsControllerUpdateMutationResponse,
	TransactionsControllerUpdatePathParams,
	TransactionsControllerUpdate404,
} from "../../schemas/transactions/transactions-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { transactionsControllerUpdate } from "../transactions-controller-update.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const transactionsControllerUpdateMutationKey = () =>
	[{ url: "/v1/transactions/:id" }] as const;

export type TransactionsControllerUpdateMutationKey = ReturnType<
	typeof transactionsControllerUpdateMutationKey
>;

export function useTransactionsControllerUpdateMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<TransactionsControllerUpdateMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = transactionsControllerUpdateMutationKey();
	return mutationOptions<
		TransactionsControllerUpdateMutationResponse,
		ResponseErrorConfig<TransactionsControllerUpdate404>,
		{
			id: TransactionsControllerUpdatePathParams["id"];
			data: TransactionsControllerUpdateMutationRequest;
		},
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return transactionsControllerUpdate(id, data, config);
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			TransactionsControllerUpdateMutationResponse,
			ResponseErrorConfig<TransactionsControllerUpdate404>,
			{
				id: TransactionsControllerUpdatePathParams["id"];
				data: TransactionsControllerUpdateMutationRequest;
			},
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<TransactionsControllerUpdateMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? transactionsControllerUpdateMutationKey();

	const baseOptions = useTransactionsControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		TransactionsControllerUpdateMutationResponse,
		ResponseErrorConfig<TransactionsControllerUpdate404>,
		{
			id: TransactionsControllerUpdatePathParams["id"];
			data: TransactionsControllerUpdateMutationRequest;
		},
		TContext
	>;

	return useMutation<
		TransactionsControllerUpdateMutationResponse,
		ResponseErrorConfig<TransactionsControllerUpdate404>,
		{
			id: TransactionsControllerUpdatePathParams["id"];
			data: TransactionsControllerUpdateMutationRequest;
		},
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		TransactionsControllerUpdateMutationResponse,
		ResponseErrorConfig<TransactionsControllerUpdate404>,
		{
			id: TransactionsControllerUpdatePathParams["id"];
			data: TransactionsControllerUpdateMutationRequest;
		},
		TContext
	>;
}
