/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	TransactionsControllerListQueryResponse,
	TransactionsControllerListQueryParams,
	TransactionsControllerList400,
} from "../../schemas/transactions/transactions-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { transactionsControllerList } from "../transactions-controller-list.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const transactionsControllerListSuspenseQueryKey = (
	params?: TransactionsControllerListQueryParams,
) => [{ url: "/v1/transactions" }, ...(params ? [params] : [])] as const;

export type TransactionsControllerListSuspenseQueryKey = ReturnType<
	typeof transactionsControllerListSuspenseQueryKey
>;

export function useTransactionsControllerListSuspenseQueryOptions(
	params?: TransactionsControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = transactionsControllerListSuspenseQueryKey(params);
	return queryOptions<
		TransactionsControllerListQueryResponse,
		ResponseErrorConfig<TransactionsControllerList400>,
		TransactionsControllerListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return transactionsControllerList(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/transactions}
 */
export function useTransactionsControllerListSuspense<
	TData = TransactionsControllerListQueryResponse,
	TQueryKey extends QueryKey = TransactionsControllerListSuspenseQueryKey,
>(
	params?: TransactionsControllerListQueryParams,
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				TransactionsControllerListQueryResponse,
				ResponseErrorConfig<TransactionsControllerList400>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionsControllerListSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{
			...useTransactionsControllerListSuspenseQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<TransactionsControllerList400>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
