/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionsControllerListMonthsQueryResponse } from "../../schemas/transactions/transactions-controller-list-months.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { transactionsControllerListMonths } from "../transactions-controller-list-months.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const transactionsControllerListMonthsSuspenseQueryKey = () =>
	[{ url: "/v1/transactions/months" }] as const;

export type TransactionsControllerListMonthsSuspenseQueryKey = ReturnType<
	typeof transactionsControllerListMonthsSuspenseQueryKey
>;

export function useTransactionsControllerListMonthsSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = transactionsControllerListMonthsSuspenseQueryKey();
	return queryOptions<
		TransactionsControllerListMonthsQueryResponse,
		ResponseErrorConfig<Error>,
		TransactionsControllerListMonthsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return transactionsControllerListMonths({
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/transactions/months}
 */
export function useTransactionsControllerListMonthsSuspense<
	TData = TransactionsControllerListMonthsQueryResponse,
	TQueryKey extends QueryKey = TransactionsControllerListMonthsSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				TransactionsControllerListMonthsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionsControllerListMonthsSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...useTransactionsControllerListMonthsSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
