/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	TransactionsControllerGetByIdQueryResponse,
	TransactionsControllerGetByIdPathParams,
	TransactionsControllerGetById404,
} from "../../schemas/transactions/transactions-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { transactionsControllerGetById } from "../transactions-controller-get-by-id.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const transactionsControllerGetByIdSuspenseQueryKey = (
	id: TransactionsControllerGetByIdPathParams["id"],
) => [{ url: "/v1/transactions/:id", params: { id: id } }] as const;

export type TransactionsControllerGetByIdSuspenseQueryKey = ReturnType<
	typeof transactionsControllerGetByIdSuspenseQueryKey
>;

export function useTransactionsControllerGetByIdSuspenseQueryOptions(
	id: TransactionsControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = transactionsControllerGetByIdSuspenseQueryKey(id);
	return queryOptions<
		TransactionsControllerGetByIdQueryResponse,
		ResponseErrorConfig<TransactionsControllerGetById404>,
		TransactionsControllerGetByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return transactionsControllerGetById(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/transactions/:id}
 */
export function useTransactionsControllerGetByIdSuspense<
	TData = TransactionsControllerGetByIdQueryResponse,
	TQueryKey extends QueryKey = TransactionsControllerGetByIdSuspenseQueryKey,
>(
	id: TransactionsControllerGetByIdPathParams["id"],
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				TransactionsControllerGetByIdQueryResponse,
				ResponseErrorConfig<TransactionsControllerGetById404>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ??
		transactionsControllerGetByIdSuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{
			...useTransactionsControllerGetByIdSuspenseQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<TransactionsControllerGetById404>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
