/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	DashboardControllerGetSummaryQueryResponse,
	DashboardControllerGetSummaryQueryParams,
	DashboardControllerGetSummary400,
	DashboardControllerGetSummary401,
} from "../../schemas/dashboard/dashboard-controller-get-summary.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { dashboardControllerGetSummary } from "../dashboard-controller-get-summary.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const dashboardControllerGetSummarySuspenseQueryKey = (
	params?: DashboardControllerGetSummaryQueryParams,
) => [{ url: "/v1/dashboard" }, ...(params ? [params] : [])] as const;

export type DashboardControllerGetSummarySuspenseQueryKey = ReturnType<
	typeof dashboardControllerGetSummarySuspenseQueryKey
>;

export function useDashboardControllerGetSummarySuspenseQueryOptions(
	params?: DashboardControllerGetSummaryQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = dashboardControllerGetSummarySuspenseQueryKey(params);
	return queryOptions<
		DashboardControllerGetSummaryQueryResponse,
		ResponseErrorConfig<
			DashboardControllerGetSummary400 | DashboardControllerGetSummary401
		>,
		DashboardControllerGetSummaryQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return dashboardControllerGetSummary(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/dashboard}
 */
export function useDashboardControllerGetSummarySuspense<
	TData = DashboardControllerGetSummaryQueryResponse,
	TQueryKey extends QueryKey = DashboardControllerGetSummarySuspenseQueryKey,
>(
	params?: DashboardControllerGetSummaryQueryParams,
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				DashboardControllerGetSummaryQueryResponse,
				ResponseErrorConfig<
					DashboardControllerGetSummary400 | DashboardControllerGetSummary401
				>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ??
		dashboardControllerGetSummarySuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{
			...useDashboardControllerGetSummarySuspenseQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<
			DashboardControllerGetSummary400 | DashboardControllerGetSummary401
		>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
