/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	DashboardControllerGetSummaryQueryResponse,
	DashboardControllerGetSummaryQueryParams,
	DashboardControllerGetSummary400,
	DashboardControllerGetSummary401,
} from "../../schemas/dashboard/dashboard-controller-get-summary.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { dashboardControllerGetSummary } from "../dashboard-controller-get-summary.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const dashboardControllerGetSummaryQueryKey = (
	params?: DashboardControllerGetSummaryQueryParams,
) => [{ url: "/v1/dashboard" }, ...(params ? [params] : [])] as const;

export type DashboardControllerGetSummaryQueryKey = ReturnType<
	typeof dashboardControllerGetSummaryQueryKey
>;

export function useDashboardControllerGetSummaryQueryOptions(
	params?: DashboardControllerGetSummaryQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = dashboardControllerGetSummaryQueryKey(params);
	return queryOptions<
		DashboardControllerGetSummaryQueryResponse,
		ResponseErrorConfig<
			DashboardControllerGetSummary400 | DashboardControllerGetSummary401
		>,
		DashboardControllerGetSummaryQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return dashboardControllerGetSummary(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/dashboard}
 */
export function useDashboardControllerGetSummary<
	TData = DashboardControllerGetSummaryQueryResponse,
	TQueryData = DashboardControllerGetSummaryQueryResponse,
	TQueryKey extends QueryKey = DashboardControllerGetSummaryQueryKey,
>(
	params?: DashboardControllerGetSummaryQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<
				DashboardControllerGetSummaryQueryResponse,
				ResponseErrorConfig<
					DashboardControllerGetSummary400 | DashboardControllerGetSummary401
				>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? dashboardControllerGetSummaryQueryKey(params);

	const query = useQuery(
		{
			...useDashboardControllerGetSummaryQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<
			DashboardControllerGetSummary400 | DashboardControllerGetSummary401
		>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
