/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	CategoriesControllerListQueryResponse,
	CategoriesControllerList401,
} from "../../schemas/categories/categories-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { categoriesControllerList } from "../categories-controller-list.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const categoriesControllerListSuspenseQueryKey = () =>
	[{ url: "/v1/categories" }] as const;

export type CategoriesControllerListSuspenseQueryKey = ReturnType<
	typeof categoriesControllerListSuspenseQueryKey
>;

export function useCategoriesControllerListSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = categoriesControllerListSuspenseQueryKey();
	return queryOptions<
		CategoriesControllerListQueryResponse,
		ResponseErrorConfig<CategoriesControllerList401>,
		CategoriesControllerListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return categoriesControllerList({
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/categories}
 */
export function useCategoriesControllerListSuspense<
	TData = CategoriesControllerListQueryResponse,
	TQueryKey extends QueryKey = CategoriesControllerListSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				CategoriesControllerListQueryResponse,
				ResponseErrorConfig<CategoriesControllerList401>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? categoriesControllerListSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...useCategoriesControllerListSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<CategoriesControllerList401>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
