/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	CategoriesControllerGetByIdQueryResponse,
	CategoriesControllerGetByIdPathParams,
	CategoriesControllerGetById401,
	CategoriesControllerGetById404,
} from "../../schemas/categories/categories-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { categoriesControllerGetById } from "../categories-controller-get-by-id.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const categoriesControllerGetByIdQueryKey = (
	id: CategoriesControllerGetByIdPathParams["id"],
) => [{ url: "/v1/categories/:id", params: { id: id } }] as const;

export type CategoriesControllerGetByIdQueryKey = ReturnType<
	typeof categoriesControllerGetByIdQueryKey
>;

export function useCategoriesControllerGetByIdQueryOptions(
	id: CategoriesControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = categoriesControllerGetByIdQueryKey(id);
	return queryOptions<
		CategoriesControllerGetByIdQueryResponse,
		ResponseErrorConfig<
			CategoriesControllerGetById401 | CategoriesControllerGetById404
		>,
		CategoriesControllerGetByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return categoriesControllerGetById(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerGetById<
	TData = CategoriesControllerGetByIdQueryResponse,
	TQueryData = CategoriesControllerGetByIdQueryResponse,
	TQueryKey extends QueryKey = CategoriesControllerGetByIdQueryKey,
>(
	id: CategoriesControllerGetByIdPathParams["id"],
	options: {
		query?: Partial<
			QueryObserverOptions<
				CategoriesControllerGetByIdQueryResponse,
				ResponseErrorConfig<
					CategoriesControllerGetById401 | CategoriesControllerGetById404
				>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? categoriesControllerGetByIdQueryKey(id);

	const query = useQuery(
		{
			...useCategoriesControllerGetByIdQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<
			CategoriesControllerGetById401 | CategoriesControllerGetById404
		>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
