/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	CategoriesControllerUpdateMutationRequest,
	CategoriesControllerUpdateMutationResponse,
	CategoriesControllerUpdatePathParams,
	CategoriesControllerUpdate401,
	CategoriesControllerUpdate403,
	CategoriesControllerUpdate404,
	CategoriesControllerUpdate409,
} from "../../schemas/categories/categories-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { categoriesControllerUpdate } from "../categories-controller-update.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const categoriesControllerUpdateMutationKey = () =>
	[{ url: "/v1/categories/:id" }] as const;

export type CategoriesControllerUpdateMutationKey = ReturnType<
	typeof categoriesControllerUpdateMutationKey
>;

export function useCategoriesControllerUpdateMutationOptions<
	TContext = unknown,
>(
	config: Partial<RequestConfig<CategoriesControllerUpdateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = categoriesControllerUpdateMutationKey();
	return mutationOptions<
		CategoriesControllerUpdateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerUpdate401
			| CategoriesControllerUpdate403
			| CategoriesControllerUpdate404
			| CategoriesControllerUpdate409
		>,
		{
			id: CategoriesControllerUpdatePathParams["id"];
			data: CategoriesControllerUpdateMutationRequest;
		},
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return categoriesControllerUpdate(id, data, config);
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerUpdateMutationResponse,
			ResponseErrorConfig<
				| CategoriesControllerUpdate401
				| CategoriesControllerUpdate403
				| CategoriesControllerUpdate404
				| CategoriesControllerUpdate409
			>,
			{
				id: CategoriesControllerUpdatePathParams["id"];
				data: CategoriesControllerUpdateMutationRequest;
			},
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<CategoriesControllerUpdateMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerUpdateMutationKey();

	const baseOptions = useCategoriesControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerUpdateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerUpdate401
			| CategoriesControllerUpdate403
			| CategoriesControllerUpdate404
			| CategoriesControllerUpdate409
		>,
		{
			id: CategoriesControllerUpdatePathParams["id"];
			data: CategoriesControllerUpdateMutationRequest;
		},
		TContext
	>;

	return useMutation<
		CategoriesControllerUpdateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerUpdate401
			| CategoriesControllerUpdate403
			| CategoriesControllerUpdate404
			| CategoriesControllerUpdate409
		>,
		{
			id: CategoriesControllerUpdatePathParams["id"];
			data: CategoriesControllerUpdateMutationRequest;
		},
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerUpdateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerUpdate401
			| CategoriesControllerUpdate403
			| CategoriesControllerUpdate404
			| CategoriesControllerUpdate409
		>,
		{
			id: CategoriesControllerUpdatePathParams["id"];
			data: CategoriesControllerUpdateMutationRequest;
		},
		TContext
	>;
}
