/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	CategoriesControllerCreateMutationRequest,
	CategoriesControllerCreateMutationResponse,
	CategoriesControllerCreate401,
	CategoriesControllerCreate403,
	CategoriesControllerCreate409,
} from "../../schemas/categories/categories-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { categoriesControllerCreate } from "../categories-controller-create.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const categoriesControllerCreateMutationKey = () =>
	[{ url: "/v1/categories" }] as const;

export type CategoriesControllerCreateMutationKey = ReturnType<
	typeof categoriesControllerCreateMutationKey
>;

export function useCategoriesControllerCreateMutationOptions<
	TContext = unknown,
>(
	config: Partial<RequestConfig<CategoriesControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = categoriesControllerCreateMutationKey();
	return mutationOptions<
		CategoriesControllerCreateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerCreate401
			| CategoriesControllerCreate403
			| CategoriesControllerCreate409
		>,
		{ data: CategoriesControllerCreateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return categoriesControllerCreate(data, config);
		},
	});
}

/**
 * {@link /v1/categories}
 */
export function useCategoriesControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerCreateMutationResponse,
			ResponseErrorConfig<
				| CategoriesControllerCreate401
				| CategoriesControllerCreate403
				| CategoriesControllerCreate409
			>,
			{ data: CategoriesControllerCreateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<CategoriesControllerCreateMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerCreateMutationKey();

	const baseOptions = useCategoriesControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerCreateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerCreate401
			| CategoriesControllerCreate403
			| CategoriesControllerCreate409
		>,
		{ data: CategoriesControllerCreateMutationRequest },
		TContext
	>;

	return useMutation<
		CategoriesControllerCreateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerCreate401
			| CategoriesControllerCreate403
			| CategoriesControllerCreate409
		>,
		{ data: CategoriesControllerCreateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerCreateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerCreate401
			| CategoriesControllerCreate403
			| CategoriesControllerCreate409
		>,
		{ data: CategoriesControllerCreateMutationRequest },
		TContext
	>;
}
