/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	CategoriesControllerRemoveMutationResponse,
	CategoriesControllerRemovePathParams,
	CategoriesControllerRemove401,
	CategoriesControllerRemove403,
	CategoriesControllerRemove404,
	CategoriesControllerRemove409,
} from "../../schemas/categories/categories-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { categoriesControllerRemove } from "../categories-controller-remove.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const categoriesControllerRemoveMutationKey = () =>
	[{ url: "/v1/categories/:id" }] as const;

export type CategoriesControllerRemoveMutationKey = ReturnType<
	typeof categoriesControllerRemoveMutationKey
>;

export function useCategoriesControllerRemoveMutationOptions<
	TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const mutationKey = categoriesControllerRemoveMutationKey();
	return mutationOptions<
		CategoriesControllerRemoveMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerRemove401
			| CategoriesControllerRemove403
			| CategoriesControllerRemove404
			| CategoriesControllerRemove409
		>,
		{ id: CategoriesControllerRemovePathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return categoriesControllerRemove(id, config);
		},
	});
}

/**
 * {@link /v1/categories/:id}
 */
export function useCategoriesControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			CategoriesControllerRemoveMutationResponse,
			ResponseErrorConfig<
				| CategoriesControllerRemove401
				| CategoriesControllerRemove403
				| CategoriesControllerRemove404
				| CategoriesControllerRemove409
			>,
			{ id: CategoriesControllerRemovePathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? categoriesControllerRemoveMutationKey();

	const baseOptions = useCategoriesControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		CategoriesControllerRemoveMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerRemove401
			| CategoriesControllerRemove403
			| CategoriesControllerRemove404
			| CategoriesControllerRemove409
		>,
		{ id: CategoriesControllerRemovePathParams["id"] },
		TContext
	>;

	return useMutation<
		CategoriesControllerRemoveMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerRemove401
			| CategoriesControllerRemove403
			| CategoriesControllerRemove404
			| CategoriesControllerRemove409
		>,
		{ id: CategoriesControllerRemovePathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		CategoriesControllerRemoveMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerRemove401
			| CategoriesControllerRemove403
			| CategoriesControllerRemove404
			| CategoriesControllerRemove409
		>,
		{ id: CategoriesControllerRemovePathParams["id"] },
		TContext
	>;
}
