/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppControllerGetHealthQueryResponse } from "../../schemas/health/app-controller-get-health.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { appControllerGetHealth } from "../app-controller-get-health.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const appControllerGetHealthQueryKey = () => [{ url: "/v1" }] as const;

export type AppControllerGetHealthQueryKey = ReturnType<
	typeof appControllerGetHealthQueryKey
>;

export function useAppControllerGetHealthQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = appControllerGetHealthQueryKey();
	return queryOptions<
		AppControllerGetHealthQueryResponse,
		ResponseErrorConfig<Error>,
		AppControllerGetHealthQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return appControllerGetHealth({
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1}
 */
export function useAppControllerGetHealth<
	TData = AppControllerGetHealthQueryResponse,
	TQueryData = AppControllerGetHealthQueryResponse,
	TQueryKey extends QueryKey = AppControllerGetHealthQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				AppControllerGetHealthQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? appControllerGetHealthQueryKey();

	const query = useQuery(
		{
			...useAppControllerGetHealthQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
