/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppControllerGetHealthQueryResponse } from "../../schemas/health/app-controller-get-health.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { appControllerGetHealth } from "../app-controller-get-health.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const appControllerGetHealthSuspenseQueryKey = () =>
	[{ url: "/v1" }] as const;

export type AppControllerGetHealthSuspenseQueryKey = ReturnType<
	typeof appControllerGetHealthSuspenseQueryKey
>;

export function useAppControllerGetHealthSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = appControllerGetHealthSuspenseQueryKey();
	return queryOptions<
		AppControllerGetHealthQueryResponse,
		ResponseErrorConfig<Error>,
		AppControllerGetHealthQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return appControllerGetHealth({
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1}
 */
export function useAppControllerGetHealthSuspense<
	TData = AppControllerGetHealthQueryResponse,
	TQueryKey extends QueryKey = AppControllerGetHealthSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				AppControllerGetHealthQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? appControllerGetHealthSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...useAppControllerGetHealthSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
