/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	AuthControllerForgotPasswordMutationRequest,
	AuthControllerForgotPasswordMutationResponse,
} from "../../schemas/auth/auth-controller-forgot-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { authControllerForgotPassword } from "../auth-controller-forgot-password.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerForgotPasswordMutationKey = () =>
	[{ url: "/v1/auth/forgot-password" }] as const;

export type AuthControllerForgotPasswordMutationKey = ReturnType<
	typeof authControllerForgotPasswordMutationKey
>;

export function useAuthControllerForgotPasswordMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<AuthControllerForgotPasswordMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = authControllerForgotPasswordMutationKey();
	return mutationOptions<
		AuthControllerForgotPasswordMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: AuthControllerForgotPasswordMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return authControllerForgotPassword(data, config);
		},
	});
}

/**
 * {@link /v1/auth/forgot-password}
 */
export function useAuthControllerForgotPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerForgotPasswordMutationResponse,
			ResponseErrorConfig<Error>,
			{ data: AuthControllerForgotPasswordMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<AuthControllerForgotPasswordMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerForgotPasswordMutationKey();

	const baseOptions = useAuthControllerForgotPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerForgotPasswordMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: AuthControllerForgotPasswordMutationRequest },
		TContext
	>;

	return useMutation<
		AuthControllerForgotPasswordMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: AuthControllerForgotPasswordMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerForgotPasswordMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: AuthControllerForgotPasswordMutationRequest },
		TContext
	>;
}
