/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	AuthControllerMeQueryResponse,
	AuthControllerMe401,
} from "../../schemas/auth/auth-controller-me.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { authControllerMe } from "../auth-controller-me.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const authControllerMeSuspenseQueryKey = () =>
	[{ url: "/v1/auth/me" }] as const;

export type AuthControllerMeSuspenseQueryKey = ReturnType<
	typeof authControllerMeSuspenseQueryKey
>;

export function useAuthControllerMeSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = authControllerMeSuspenseQueryKey();
	return queryOptions<
		AuthControllerMeQueryResponse,
		ResponseErrorConfig<AuthControllerMe401>,
		AuthControllerMeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return authControllerMe({ ...config, signal: config.signal ?? signal });
		},
	});
}

/**
 * {@link /v1/auth/me}
 */
export function useAuthControllerMeSuspense<
	TData = AuthControllerMeQueryResponse,
	TQueryKey extends QueryKey = AuthControllerMeSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				AuthControllerMeQueryResponse,
				ResponseErrorConfig<AuthControllerMe401>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? authControllerMeSuspenseQueryKey();

	const query = useSuspenseQuery(
		{
			...useAuthControllerMeSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<AuthControllerMe401>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
