/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	AuthControllerMeQueryResponse,
	AuthControllerMe401,
} from "../../schemas/auth/auth-controller-me.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { authControllerMe } from "../auth-controller-me.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const authControllerMeQueryKey = () => [{ url: "/v1/auth/me" }] as const;

export type AuthControllerMeQueryKey = ReturnType<
	typeof authControllerMeQueryKey
>;

export function useAuthControllerMeQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = authControllerMeQueryKey();
	return queryOptions<
		AuthControllerMeQueryResponse,
		ResponseErrorConfig<AuthControllerMe401>,
		AuthControllerMeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return authControllerMe({ ...config, signal: config.signal ?? signal });
		},
	});
}

/**
 * {@link /v1/auth/me}
 */
export function useAuthControllerMe<
	TData = AuthControllerMeQueryResponse,
	TQueryData = AuthControllerMeQueryResponse,
	TQueryKey extends QueryKey = AuthControllerMeQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				AuthControllerMeQueryResponse,
				ResponseErrorConfig<AuthControllerMe401>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey = resolvedOptions?.queryKey ?? authControllerMeQueryKey();

	const query = useQuery(
		{
			...useAuthControllerMeQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<AuthControllerMe401>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
