/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthControllerLogoutMutationResponse } from "../../schemas/auth/auth-controller-logout.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { authControllerLogout } from "../auth-controller-logout.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerLogoutMutationKey = () =>
	[{ url: "/v1/auth/logout" }] as const;

export type AuthControllerLogoutMutationKey = ReturnType<
	typeof authControllerLogoutMutationKey
>;

export function useAuthControllerLogoutMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const mutationKey = authControllerLogoutMutationKey();
	return mutationOptions<
		AuthControllerLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>({
		mutationKey,
		mutationFn: async () => {
			return authControllerLogout(config);
		},
	});
}

/**
 * {@link /v1/auth/logout}
 */
export function useAuthControllerLogout<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerLogoutMutationResponse,
			ResponseErrorConfig<Error>,
			void,
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerLogoutMutationKey();

	const baseOptions = useAuthControllerLogoutMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>;

	return useMutation<
		AuthControllerLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		void,
		TContext
	>;
}
