/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	AuthControllerLoginMutationRequest,
	AuthControllerLoginMutationResponse,
	AuthControllerLogin401,
} from "../../schemas/auth/auth-controller-login.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { authControllerLogin } from "../auth-controller-login.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerLoginMutationKey = () =>
	[{ url: "/v1/auth/login" }] as const;

export type AuthControllerLoginMutationKey = ReturnType<
	typeof authControllerLoginMutationKey
>;

export function useAuthControllerLoginMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = authControllerLoginMutationKey();
	return mutationOptions<
		AuthControllerLoginMutationResponse,
		ResponseErrorConfig<AuthControllerLogin401>,
		{ data: AuthControllerLoginMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return authControllerLogin(data, config);
		},
	});
}

/**
 * {@link /v1/auth/login}
 */
export function useAuthControllerLogin<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerLoginMutationResponse,
			ResponseErrorConfig<AuthControllerLogin401>,
			{ data: AuthControllerLoginMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & {
			client?: Client;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerLoginMutationKey();

	const baseOptions = useAuthControllerLoginMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerLoginMutationResponse,
		ResponseErrorConfig<AuthControllerLogin401>,
		{ data: AuthControllerLoginMutationRequest },
		TContext
	>;

	return useMutation<
		AuthControllerLoginMutationResponse,
		ResponseErrorConfig<AuthControllerLogin401>,
		{ data: AuthControllerLoginMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerLoginMutationResponse,
		ResponseErrorConfig<AuthControllerLogin401>,
		{ data: AuthControllerLoginMutationRequest },
		TContext
	>;
}
