/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	AuthControllerResetPasswordMutationRequest,
	AuthControllerResetPasswordMutationResponse,
	AuthControllerResetPassword401,
} from "../../schemas/auth/auth-controller-reset-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { authControllerResetPassword } from "../auth-controller-reset-password.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authControllerResetPasswordMutationKey = () =>
	[{ url: "/v1/auth/reset-password" }] as const;

export type AuthControllerResetPasswordMutationKey = ReturnType<
	typeof authControllerResetPasswordMutationKey
>;

export function useAuthControllerResetPasswordMutationOptions<
	TContext = unknown,
>(
	config: Partial<RequestConfig<AuthControllerResetPasswordMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = authControllerResetPasswordMutationKey();
	return mutationOptions<
		AuthControllerResetPasswordMutationResponse,
		ResponseErrorConfig<AuthControllerResetPassword401>,
		{ data: AuthControllerResetPasswordMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return authControllerResetPassword(data, config);
		},
	});
}

/**
 * {@link /v1/auth/reset-password}
 */
export function useAuthControllerResetPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			AuthControllerResetPasswordMutationResponse,
			ResponseErrorConfig<AuthControllerResetPassword401>,
			{ data: AuthControllerResetPasswordMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<AuthControllerResetPasswordMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? authControllerResetPasswordMutationKey();

	const baseOptions = useAuthControllerResetPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		AuthControllerResetPasswordMutationResponse,
		ResponseErrorConfig<AuthControllerResetPassword401>,
		{ data: AuthControllerResetPasswordMutationRequest },
		TContext
	>;

	return useMutation<
		AuthControllerResetPasswordMutationResponse,
		ResponseErrorConfig<AuthControllerResetPassword401>,
		{ data: AuthControllerResetPasswordMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		AuthControllerResetPasswordMutationResponse,
		ResponseErrorConfig<AuthControllerResetPassword401>,
		{ data: AuthControllerResetPasswordMutationRequest },
		TContext
	>;
}
