/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ResetPasswordDto } from "../reset-password-dto.ts";

/**
 * @example [object Object]
 */
export type AuthControllerResetPassword200 = any;

/**
 * @description Token de recuperação inválido ou expirado
 */
export type AuthControllerResetPassword401 = any;

export type AuthControllerResetPasswordMutationRequest = ResetPasswordDto;

export type AuthControllerResetPasswordMutationResponse =
	AuthControllerResetPassword200;

export type AuthControllerResetPasswordMutation = {
	Response: AuthControllerResetPassword200;
	Request: AuthControllerResetPasswordMutationRequest;
	Errors: AuthControllerResetPassword401;
};
