/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example [object Object]
 */
export type AuthControllerLogout200 = any;

export type AuthControllerLogoutMutationResponse = AuthControllerLogout200;

export type AuthControllerLogoutMutation = {
	Response: AuthControllerLogout200;
	Errors: any;
};
