/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Dados do usuário autenticado
 * @example [object Object]
 */
export type AuthControllerMe200 = any;

/**
 * @description Não autenticado
 */
export type AuthControllerMe401 = any;

export type AuthControllerMeQueryResponse = AuthControllerMe200;

export type AuthControllerMeQuery = {
	Response: AuthControllerMe200;
	Errors: AuthControllerMe401;
};
