/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthControllerLoginMutationRequest,
	AuthControllerLoginMutationResponse,
	AuthControllerLogin401,
} from "../schemas/auth/auth-controller-login.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAuthControllerLoginUrl() {
	const res = { method: "POST", url: `/v1/auth/login` as const };
	return res;
}

/**
 * {@link /v1/auth/login}
 */
export async function authControllerLogin(
	data: AuthControllerLoginMutationRequest,
	config: Partial<RequestConfig<AuthControllerLoginMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		AuthControllerLoginMutationResponse,
		ResponseErrorConfig<AuthControllerLogin401>,
		AuthControllerLoginMutationRequest
	>({
		method: "POST",
		url: getAuthControllerLoginUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
