/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthControllerResetPasswordMutationRequest,
	AuthControllerResetPasswordMutationResponse,
	AuthControllerResetPassword401,
} from "../schemas/auth/auth-controller-reset-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAuthControllerResetPasswordUrl() {
	const res = { method: "POST", url: `/v1/auth/reset-password` as const };
	return res;
}

/**
 * {@link /v1/auth/reset-password}
 */
export async function authControllerResetPassword(
	data: AuthControllerResetPasswordMutationRequest,
	config: Partial<RequestConfig<AuthControllerResetPasswordMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		AuthControllerResetPasswordMutationResponse,
		ResponseErrorConfig<AuthControllerResetPassword401>,
		AuthControllerResetPasswordMutationRequest
	>({
		method: "POST",
		url: getAuthControllerResetPasswordUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
