/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthControllerForgotPasswordMutationRequest,
	AuthControllerForgotPasswordMutationResponse,
} from "../schemas/auth/auth-controller-forgot-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAuthControllerForgotPasswordUrl() {
	const res = { method: "POST", url: `/v1/auth/forgot-password` as const };
	return res;
}

/**
 * {@link /v1/auth/forgot-password}
 */
export async function authControllerForgotPassword(
	data: AuthControllerForgotPasswordMutationRequest,
	config: Partial<
		RequestConfig<AuthControllerForgotPasswordMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		AuthControllerForgotPasswordMutationResponse,
		ResponseErrorConfig<Error>,
		AuthControllerForgotPasswordMutationRequest
	>({
		method: "POST",
		url: getAuthControllerForgotPasswordUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
