/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthControllerLogoutMutationResponse } from "../schemas/auth/auth-controller-logout.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAuthControllerLogoutUrl() {
	const res = { method: "POST", url: `/v1/auth/logout` as const };
	return res;
}

/**
 * {@link /v1/auth/logout}
 */
export async function authControllerLogout(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		AuthControllerLogoutMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "POST",
		url: getAuthControllerLogoutUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
