/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	AuthControllerMeQueryResponse,
	AuthControllerMe401,
} from "../schemas/auth/auth-controller-me.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAuthControllerMeUrl() {
	const res = { method: "GET", url: `/v1/auth/me` as const };
	return res;
}

/**
 * {@link /v1/auth/me}
 */
export async function authControllerMe(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		AuthControllerMeQueryResponse,
		ResponseErrorConfig<AuthControllerMe401>,
		unknown
	>({
		method: "GET",
		url: getAuthControllerMeUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
