/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	DashboardControllerGetSummaryQueryResponse,
	DashboardControllerGetSummaryQueryParams,
	DashboardControllerGetSummary400,
	DashboardControllerGetSummary401,
} from "../schemas/dashboard/dashboard-controller-get-summary.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getDashboardControllerGetSummaryUrl() {
	const res = { method: "GET", url: `/v1/dashboard` as const };
	return res;
}

/**
 * {@link /v1/dashboard}
 */
export async function dashboardControllerGetSummary(
	params?: DashboardControllerGetSummaryQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		DashboardControllerGetSummaryQueryResponse,
		ResponseErrorConfig<
			DashboardControllerGetSummary400 | DashboardControllerGetSummary401
		>,
		unknown
	>({
		method: "GET",
		url: getDashboardControllerGetSummaryUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
