/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	CategoriesControllerGetByIdQueryResponse,
	CategoriesControllerGetByIdPathParams,
	CategoriesControllerGetById401,
	CategoriesControllerGetById404,
} from "../schemas/categories/categories-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getCategoriesControllerGetByIdUrl(
	id: CategoriesControllerGetByIdPathParams["id"],
) {
	const res = { method: "GET", url: `/v1/categories/${id}` as const };
	return res;
}

/**
 * {@link /v1/categories/:id}
 */
export async function categoriesControllerGetById(
	id: CategoriesControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		CategoriesControllerGetByIdQueryResponse,
		ResponseErrorConfig<
			CategoriesControllerGetById401 | CategoriesControllerGetById404
		>,
		unknown
	>({
		method: "GET",
		url: getCategoriesControllerGetByIdUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
