/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	CategoriesControllerCreateMutationRequest,
	CategoriesControllerCreateMutationResponse,
	CategoriesControllerCreate401,
	CategoriesControllerCreate403,
	CategoriesControllerCreate409,
} from "../schemas/categories/categories-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getCategoriesControllerCreateUrl() {
	const res = { method: "POST", url: `/v1/categories` as const };
	return res;
}

/**
 * {@link /v1/categories}
 */
export async function categoriesControllerCreate(
	data: CategoriesControllerCreateMutationRequest,
	config: Partial<RequestConfig<CategoriesControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		CategoriesControllerCreateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerCreate401
			| CategoriesControllerCreate403
			| CategoriesControllerCreate409
		>,
		CategoriesControllerCreateMutationRequest
	>({
		method: "POST",
		url: getCategoriesControllerCreateUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
