/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	CategoriesControllerRemoveMutationResponse,
	CategoriesControllerRemovePathParams,
	CategoriesControllerRemove401,
	CategoriesControllerRemove403,
	CategoriesControllerRemove404,
	CategoriesControllerRemove409,
} from "../schemas/categories/categories-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getCategoriesControllerRemoveUrl(
	id: CategoriesControllerRemovePathParams["id"],
) {
	const res = { method: "DELETE", url: `/v1/categories/${id}` as const };
	return res;
}

/**
 * {@link /v1/categories/:id}
 */
export async function categoriesControllerRemove(
	id: CategoriesControllerRemovePathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		CategoriesControllerRemoveMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerRemove401
			| CategoriesControllerRemove403
			| CategoriesControllerRemove404
			| CategoriesControllerRemove409
		>,
		unknown
	>({
		method: "DELETE",
		url: getCategoriesControllerRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
