/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	CategoriesControllerListQueryResponse,
	CategoriesControllerList401,
} from "../schemas/categories/categories-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getCategoriesControllerListUrl() {
	const res = { method: "GET", url: `/v1/categories` as const };
	return res;
}

/**
 * {@link /v1/categories}
 */
export async function categoriesControllerList(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		CategoriesControllerListQueryResponse,
		ResponseErrorConfig<CategoriesControllerList401>,
		unknown
	>({
		method: "GET",
		url: getCategoriesControllerListUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
