/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	CategoriesControllerUpdateMutationRequest,
	CategoriesControllerUpdateMutationResponse,
	CategoriesControllerUpdatePathParams,
	CategoriesControllerUpdate401,
	CategoriesControllerUpdate403,
	CategoriesControllerUpdate404,
	CategoriesControllerUpdate409,
} from "../schemas/categories/categories-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getCategoriesControllerUpdateUrl(
	id: CategoriesControllerUpdatePathParams["id"],
) {
	const res = { method: "PUT", url: `/v1/categories/${id}` as const };
	return res;
}

/**
 * {@link /v1/categories/:id}
 */
export async function categoriesControllerUpdate(
	id: CategoriesControllerUpdatePathParams["id"],
	data: CategoriesControllerUpdateMutationRequest,
	config: Partial<RequestConfig<CategoriesControllerUpdateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		CategoriesControllerUpdateMutationResponse,
		ResponseErrorConfig<
			| CategoriesControllerUpdate401
			| CategoriesControllerUpdate403
			| CategoriesControllerUpdate404
			| CategoriesControllerUpdate409
		>,
		CategoriesControllerUpdateMutationRequest
	>({
		method: "PUT",
		url: getCategoriesControllerUpdateUrl(id).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
