/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example [object Object]
 */
export type AppControllerGetHealth200 = any;

export type AppControllerGetHealthQueryResponse = AppControllerGetHealth200;

export type AppControllerGetHealthQuery = {
	Response: AppControllerGetHealth200;
	Errors: any;
};
