/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerUpdateByAdminMutationRequest,
	UsersControllerUpdateByAdminMutationResponse,
	UsersControllerUpdateByAdminPathParams,
	UsersControllerUpdateByAdmin401,
	UsersControllerUpdateByAdmin403,
	UsersControllerUpdateByAdmin404,
	UsersControllerUpdateByAdmin409,
} from "../../schemas/users/users-controller-update-by-admin.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { usersControllerUpdateByAdmin } from "../users-controller-update-by-admin.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerUpdateByAdminMutationKey = () =>
	[{ url: "/v1/users/:id" }] as const;

export type UsersControllerUpdateByAdminMutationKey = ReturnType<
	typeof usersControllerUpdateByAdminMutationKey
>;

export function usersControllerUpdateByAdminMutationOptions<TContext = unknown>(
	config: Partial<
		RequestConfig<UsersControllerUpdateByAdminMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = usersControllerUpdateByAdminMutationKey();
	return mutationOptions<
		UsersControllerUpdateByAdminMutationResponse,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdmin401
			| UsersControllerUpdateByAdmin403
			| UsersControllerUpdateByAdmin404
			| UsersControllerUpdateByAdmin409
		>,
		{
			id: UsersControllerUpdateByAdminPathParams["id"];
			data: UsersControllerUpdateByAdminMutationRequest;
		},
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return usersControllerUpdateByAdmin(id, data, config);
		},
	});
}

/**
 * {@link /v1/users/:id}
 */
export function useUsersControllerUpdateByAdmin<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerUpdateByAdminMutationResponse,
			ResponseErrorConfig<
				| UsersControllerUpdateByAdmin401
				| UsersControllerUpdateByAdmin403
				| UsersControllerUpdateByAdmin404
				| UsersControllerUpdateByAdmin409
			>,
			{
				id: UsersControllerUpdateByAdminPathParams["id"];
				data: UsersControllerUpdateByAdminMutationRequest;
			},
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<UsersControllerUpdateByAdminMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerUpdateByAdminMutationKey();

	const baseOptions = usersControllerUpdateByAdminMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerUpdateByAdminMutationResponse,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdmin401
			| UsersControllerUpdateByAdmin403
			| UsersControllerUpdateByAdmin404
			| UsersControllerUpdateByAdmin409
		>,
		{
			id: UsersControllerUpdateByAdminPathParams["id"];
			data: UsersControllerUpdateByAdminMutationRequest;
		},
		TContext
	>;

	return useMutation<
		UsersControllerUpdateByAdminMutationResponse,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdmin401
			| UsersControllerUpdateByAdmin403
			| UsersControllerUpdateByAdmin404
			| UsersControllerUpdateByAdmin409
		>,
		{
			id: UsersControllerUpdateByAdminPathParams["id"];
			data: UsersControllerUpdateByAdminMutationRequest;
		},
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerUpdateByAdminMutationResponse,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdmin401
			| UsersControllerUpdateByAdmin403
			| UsersControllerUpdateByAdmin404
			| UsersControllerUpdateByAdmin409
		>,
		{
			id: UsersControllerUpdateByAdminPathParams["id"];
			data: UsersControllerUpdateByAdminMutationRequest;
		},
		TContext
	>;
}
