/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerAdminResetPasswordMutationRequest,
	UsersControllerAdminResetPasswordMutationResponse,
	UsersControllerAdminResetPasswordPathParams,
	UsersControllerAdminResetPassword401,
	UsersControllerAdminResetPassword403,
	UsersControllerAdminResetPassword404,
} from "../../schemas/users/users-controller-admin-reset-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { usersControllerAdminResetPassword } from "../users-controller-admin-reset-password.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerAdminResetPasswordMutationKey = () =>
	[{ url: "/v1/users/:id/password" }] as const;

export type UsersControllerAdminResetPasswordMutationKey = ReturnType<
	typeof usersControllerAdminResetPasswordMutationKey
>;

export function usersControllerAdminResetPasswordMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<UsersControllerAdminResetPasswordMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = usersControllerAdminResetPasswordMutationKey();
	return mutationOptions<
		UsersControllerAdminResetPasswordMutationResponse,
		ResponseErrorConfig<
			| UsersControllerAdminResetPassword401
			| UsersControllerAdminResetPassword403
			| UsersControllerAdminResetPassword404
		>,
		{
			id: UsersControllerAdminResetPasswordPathParams["id"];
			data: UsersControllerAdminResetPasswordMutationRequest;
		},
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return usersControllerAdminResetPassword(id, data, config);
		},
	});
}

/**
 * {@link /v1/users/:id/password}
 */
export function useUsersControllerAdminResetPassword<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerAdminResetPasswordMutationResponse,
			ResponseErrorConfig<
				| UsersControllerAdminResetPassword401
				| UsersControllerAdminResetPassword403
				| UsersControllerAdminResetPassword404
			>,
			{
				id: UsersControllerAdminResetPasswordPathParams["id"];
				data: UsersControllerAdminResetPasswordMutationRequest;
			},
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<UsersControllerAdminResetPasswordMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ??
		usersControllerAdminResetPasswordMutationKey();

	const baseOptions = usersControllerAdminResetPasswordMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerAdminResetPasswordMutationResponse,
		ResponseErrorConfig<
			| UsersControllerAdminResetPassword401
			| UsersControllerAdminResetPassword403
			| UsersControllerAdminResetPassword404
		>,
		{
			id: UsersControllerAdminResetPasswordPathParams["id"];
			data: UsersControllerAdminResetPasswordMutationRequest;
		},
		TContext
	>;

	return useMutation<
		UsersControllerAdminResetPasswordMutationResponse,
		ResponseErrorConfig<
			| UsersControllerAdminResetPassword401
			| UsersControllerAdminResetPassword403
			| UsersControllerAdminResetPassword404
		>,
		{
			id: UsersControllerAdminResetPasswordPathParams["id"];
			data: UsersControllerAdminResetPasswordMutationRequest;
		},
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerAdminResetPasswordMutationResponse,
		ResponseErrorConfig<
			| UsersControllerAdminResetPassword401
			| UsersControllerAdminResetPassword403
			| UsersControllerAdminResetPassword404
		>,
		{
			id: UsersControllerAdminResetPasswordPathParams["id"];
			data: UsersControllerAdminResetPasswordMutationRequest;
		},
		TContext
	>;
}
