/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerUpdateOwnProfileMutationRequest,
	UsersControllerUpdateOwnProfileMutationResponse,
	UsersControllerUpdateOwnProfile401,
	UsersControllerUpdateOwnProfile409,
} from "../../schemas/users/users-controller-update-own-profile.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { usersControllerUpdateOwnProfile } from "../users-controller-update-own-profile.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerUpdateOwnProfileMutationKey = () =>
	[{ url: "/v1/users/me" }] as const;

export type UsersControllerUpdateOwnProfileMutationKey = ReturnType<
	typeof usersControllerUpdateOwnProfileMutationKey
>;

export function usersControllerUpdateOwnProfileMutationOptions<
	TContext = unknown,
>(
	config: Partial<
		RequestConfig<UsersControllerUpdateOwnProfileMutationRequest>
	> & { client?: Client } = {},
) {
	const mutationKey = usersControllerUpdateOwnProfileMutationKey();
	return mutationOptions<
		UsersControllerUpdateOwnProfileMutationResponse,
		ResponseErrorConfig<
			UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
		>,
		{ data: UsersControllerUpdateOwnProfileMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return usersControllerUpdateOwnProfile(data, config);
		},
	});
}

/**
 * {@link /v1/users/me}
 */
export function useUsersControllerUpdateOwnProfile<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerUpdateOwnProfileMutationResponse,
			ResponseErrorConfig<
				UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
			>,
			{ data: UsersControllerUpdateOwnProfileMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<UsersControllerUpdateOwnProfileMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerUpdateOwnProfileMutationKey();

	const baseOptions = usersControllerUpdateOwnProfileMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerUpdateOwnProfileMutationResponse,
		ResponseErrorConfig<
			UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
		>,
		{ data: UsersControllerUpdateOwnProfileMutationRequest },
		TContext
	>;

	return useMutation<
		UsersControllerUpdateOwnProfileMutationResponse,
		ResponseErrorConfig<
			UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
		>,
		{ data: UsersControllerUpdateOwnProfileMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerUpdateOwnProfileMutationResponse,
		ResponseErrorConfig<
			UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
		>,
		{ data: UsersControllerUpdateOwnProfileMutationRequest },
		TContext
	>;
}
