/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerListQueryResponse,
	UsersControllerListQueryParams,
	UsersControllerList401,
	UsersControllerList403,
} from "../../schemas/users/users-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { usersControllerList } from "../users-controller-list.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersControllerListQueryKey = (
	params?: UsersControllerListQueryParams,
) => [{ url: "/v1/users" }, ...(params ? [params] : [])] as const;

export type UsersControllerListQueryKey = ReturnType<
	typeof usersControllerListQueryKey
>;

export function usersControllerListQueryOptions(
	params?: UsersControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = usersControllerListQueryKey(params);
	return queryOptions<
		UsersControllerListQueryResponse,
		ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>,
		UsersControllerListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return usersControllerList(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/users}
 */
export function useUsersControllerList<
	TData = UsersControllerListQueryResponse,
	TQueryData = UsersControllerListQueryResponse,
	TQueryKey extends QueryKey = UsersControllerListQueryKey,
>(
	params?: UsersControllerListQueryParams,
	options: {
		query?: Partial<
			QueryObserverOptions<
				UsersControllerListQueryResponse,
				ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? usersControllerListQueryKey(params);

	const query = useQuery(
		{
			...usersControllerListQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
