/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerListQueryResponse,
	UsersControllerListQueryParams,
	UsersControllerList401,
	UsersControllerList403,
} from "../../schemas/users/users-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { usersControllerList } from "../users-controller-list.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const usersControllerListSuspenseQueryKey = (
	params?: UsersControllerListQueryParams,
) => [{ url: "/v1/users" }, ...(params ? [params] : [])] as const;

export type UsersControllerListSuspenseQueryKey = ReturnType<
	typeof usersControllerListSuspenseQueryKey
>;

export function usersControllerListSuspenseQueryOptions(
	params?: UsersControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = usersControllerListSuspenseQueryKey(params);
	return queryOptions<
		UsersControllerListQueryResponse,
		ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>,
		UsersControllerListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return usersControllerList(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/users}
 */
export function useUsersControllerListSuspense<
	TData = UsersControllerListQueryResponse,
	TQueryKey extends QueryKey = UsersControllerListSuspenseQueryKey,
>(
	params?: UsersControllerListQueryParams,
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				UsersControllerListQueryResponse,
				ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? usersControllerListSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{
			...usersControllerListSuspenseQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
