/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	UsersControllerCreateMutationRequest,
	UsersControllerCreateMutationResponse,
	UsersControllerCreate401,
	UsersControllerCreate403,
	UsersControllerCreate409,
} from "../../schemas/users/users-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { usersControllerCreate } from "../users-controller-create.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const usersControllerCreateMutationKey = () =>
	[{ url: "/v1/users" }] as const;

export type UsersControllerCreateMutationKey = ReturnType<
	typeof usersControllerCreateMutationKey
>;

export function usersControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<UsersControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = usersControllerCreateMutationKey();
	return mutationOptions<
		UsersControllerCreateMutationResponse,
		ResponseErrorConfig<
			| UsersControllerCreate401
			| UsersControllerCreate403
			| UsersControllerCreate409
		>,
		{ data: UsersControllerCreateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return usersControllerCreate(data, config);
		},
	});
}

/**
 * {@link /v1/users}
 */
export function useUsersControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			UsersControllerCreateMutationResponse,
			ResponseErrorConfig<
				| UsersControllerCreate401
				| UsersControllerCreate403
				| UsersControllerCreate409
			>,
			{ data: UsersControllerCreateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<UsersControllerCreateMutationRequest>> & {
			client?: Client;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? usersControllerCreateMutationKey();

	const baseOptions = usersControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		UsersControllerCreateMutationResponse,
		ResponseErrorConfig<
			| UsersControllerCreate401
			| UsersControllerCreate403
			| UsersControllerCreate409
		>,
		{ data: UsersControllerCreateMutationRequest },
		TContext
	>;

	return useMutation<
		UsersControllerCreateMutationResponse,
		ResponseErrorConfig<
			| UsersControllerCreate401
			| UsersControllerCreate403
			| UsersControllerCreate409
		>,
		{ data: UsersControllerCreateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		UsersControllerCreateMutationResponse,
		ResponseErrorConfig<
			| UsersControllerCreate401
			| UsersControllerCreate403
			| UsersControllerCreate409
		>,
		{ data: UsersControllerCreateMutationRequest },
		TContext
	>;
}
