/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateOwnProfileDto } from "../update-own-profile-dto.ts";

/**
 * @description Perfil atualizado com sucesso
 */
export type UsersControllerUpdateOwnProfile200 = any;

/**
 * @description Não autenticado
 */
export type UsersControllerUpdateOwnProfile401 = any;

/**
 * @description E-mail já está em uso
 */
export type UsersControllerUpdateOwnProfile409 = any;

export type UsersControllerUpdateOwnProfileMutationRequest =
	UpdateOwnProfileDto;

export type UsersControllerUpdateOwnProfileMutationResponse =
	UsersControllerUpdateOwnProfile200;

export type UsersControllerUpdateOwnProfileMutation = {
	Response: UsersControllerUpdateOwnProfile200;
	Request: UsersControllerUpdateOwnProfileMutationRequest;
	Errors:
		| UsersControllerUpdateOwnProfile401
		| UsersControllerUpdateOwnProfile409;
};
