/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateUserByAdminDto } from "../update-user-by-admin-dto.ts";

export type UsersControllerUpdateByAdminPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Usuário atualizado com sucesso
 */
export type UsersControllerUpdateByAdmin200 = any;

/**
 * @description Não autenticado
 */
export type UsersControllerUpdateByAdmin401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type UsersControllerUpdateByAdmin403 = any;

/**
 * @description Usuário não encontrado
 */
export type UsersControllerUpdateByAdmin404 = any;

/**
 * @description E-mail já está em uso
 */
export type UsersControllerUpdateByAdmin409 = any;

export type UsersControllerUpdateByAdminMutationRequest = UpdateUserByAdminDto;

export type UsersControllerUpdateByAdminMutationResponse =
	UsersControllerUpdateByAdmin200;

export type UsersControllerUpdateByAdminMutation = {
	Response: UsersControllerUpdateByAdmin200;
	Request: UsersControllerUpdateByAdminMutationRequest;
	PathParams: UsersControllerUpdateByAdminPathParams;
	Errors:
		| UsersControllerUpdateByAdmin401
		| UsersControllerUpdateByAdmin403
		| UsersControllerUpdateByAdmin404
		| UsersControllerUpdateByAdmin409;
};
