/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UsersControllerListQueryParams = {
	/**
	 * @minLength 1
	 * @default 1
	 * @type number | undefined
	 */
	page?: number;
	/**
	 * @minLength 1
	 * @maxLength 100
	 * @default 10
	 * @type number | undefined
	 */
	perPage?: number;
	/**
	 * @description Busca por nome ou e-mail
	 * @type string | undefined
	 */
	search?: string;
};

/**
 * @description Usuários listados com sucesso
 */
export type UsersControllerList200 = any;

/**
 * @description Não autenticado
 */
export type UsersControllerList401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type UsersControllerList403 = any;

export type UsersControllerListQueryResponse = UsersControllerList200;

export type UsersControllerListQuery = {
	Response: UsersControllerList200;
	QueryParams: UsersControllerListQueryParams;
	Errors: UsersControllerList401 | UsersControllerList403;
};
