/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from "../create-user-dto.ts";

/**
 * @description Usuário criado com sucesso
 */
export type UsersControllerCreate201 = any;

/**
 * @description Não autenticado
 */
export type UsersControllerCreate401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type UsersControllerCreate403 = any;

/**
 * @description E-mail já está em uso
 */
export type UsersControllerCreate409 = any;

export type UsersControllerCreateMutationRequest = CreateUserDto;

export type UsersControllerCreateMutationResponse = UsersControllerCreate201;

export type UsersControllerCreateMutation = {
	Response: UsersControllerCreate201;
	Request: UsersControllerCreateMutationRequest;
	Errors:
		| UsersControllerCreate401
		| UsersControllerCreate403
		| UsersControllerCreate409;
};
