/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerListQueryResponse,
	UsersControllerListQueryParams,
	UsersControllerList401,
	UsersControllerList403,
} from "../schemas/users/users-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getUsersControllerListUrl() {
	const res = { method: "GET", url: `/v1/users` as const };
	return res;
}

/**
 * {@link /v1/users}
 */
export async function usersControllerList(
	params?: UsersControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		UsersControllerListQueryResponse,
		ResponseErrorConfig<UsersControllerList401 | UsersControllerList403>,
		unknown
	>({
		method: "GET",
		url: getUsersControllerListUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
