/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerCreateMutationRequest,
	UsersControllerCreateMutationResponse,
	UsersControllerCreate401,
	UsersControllerCreate403,
	UsersControllerCreate409,
} from "../schemas/users/users-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getUsersControllerCreateUrl() {
	const res = { method: "POST", url: `/v1/users` as const };
	return res;
}

/**
 * {@link /v1/users}
 */
export async function usersControllerCreate(
	data: UsersControllerCreateMutationRequest,
	config: Partial<RequestConfig<UsersControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UsersControllerCreateMutationResponse,
		ResponseErrorConfig<
			| UsersControllerCreate401
			| UsersControllerCreate403
			| UsersControllerCreate409
		>,
		UsersControllerCreateMutationRequest
	>({
		method: "POST",
		url: getUsersControllerCreateUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
