/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerAdminResetPasswordMutationRequest,
	UsersControllerAdminResetPasswordMutationResponse,
	UsersControllerAdminResetPasswordPathParams,
	UsersControllerAdminResetPassword401,
	UsersControllerAdminResetPassword403,
	UsersControllerAdminResetPassword404,
} from "../schemas/users/users-controller-admin-reset-password.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getUsersControllerAdminResetPasswordUrl(
	id: UsersControllerAdminResetPasswordPathParams["id"],
) {
	const res = { method: "PUT", url: `/v1/users/${id}/password` as const };
	return res;
}

/**
 * {@link /v1/users/:id/password}
 */
export async function usersControllerAdminResetPassword(
	id: UsersControllerAdminResetPasswordPathParams["id"],
	data: UsersControllerAdminResetPasswordMutationRequest,
	config: Partial<
		RequestConfig<UsersControllerAdminResetPasswordMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UsersControllerAdminResetPasswordMutationResponse,
		ResponseErrorConfig<
			| UsersControllerAdminResetPassword401
			| UsersControllerAdminResetPassword403
			| UsersControllerAdminResetPassword404
		>,
		UsersControllerAdminResetPasswordMutationRequest
	>({
		method: "PUT",
		url: getUsersControllerAdminResetPasswordUrl(id).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
