/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerUpdateByAdminMutationRequest,
	UsersControllerUpdateByAdminMutationResponse,
	UsersControllerUpdateByAdminPathParams,
	UsersControllerUpdateByAdmin401,
	UsersControllerUpdateByAdmin403,
	UsersControllerUpdateByAdmin404,
	UsersControllerUpdateByAdmin409,
} from "../schemas/users/users-controller-update-by-admin.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getUsersControllerUpdateByAdminUrl(
	id: UsersControllerUpdateByAdminPathParams["id"],
) {
	const res = { method: "PUT", url: `/v1/users/${id}` as const };
	return res;
}

/**
 * {@link /v1/users/:id}
 */
export async function usersControllerUpdateByAdmin(
	id: UsersControllerUpdateByAdminPathParams["id"],
	data: UsersControllerUpdateByAdminMutationRequest,
	config: Partial<
		RequestConfig<UsersControllerUpdateByAdminMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UsersControllerUpdateByAdminMutationResponse,
		ResponseErrorConfig<
			| UsersControllerUpdateByAdmin401
			| UsersControllerUpdateByAdmin403
			| UsersControllerUpdateByAdmin404
			| UsersControllerUpdateByAdmin409
		>,
		UsersControllerUpdateByAdminMutationRequest
	>({
		method: "PUT",
		url: getUsersControllerUpdateByAdminUrl(id).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
