/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	UsersControllerUpdateOwnProfileMutationRequest,
	UsersControllerUpdateOwnProfileMutationResponse,
	UsersControllerUpdateOwnProfile401,
	UsersControllerUpdateOwnProfile409,
} from "../schemas/users/users-controller-update-own-profile.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getUsersControllerUpdateOwnProfileUrl() {
	const res = { method: "PUT", url: `/v1/users/me` as const };
	return res;
}

/**
 * {@link /v1/users/me}
 */
export async function usersControllerUpdateOwnProfile(
	data: UsersControllerUpdateOwnProfileMutationRequest,
	config: Partial<
		RequestConfig<UsersControllerUpdateOwnProfileMutationRequest>
	> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		UsersControllerUpdateOwnProfileMutationResponse,
		ResponseErrorConfig<
			UsersControllerUpdateOwnProfile401 | UsersControllerUpdateOwnProfile409
		>,
		UsersControllerUpdateOwnProfileMutationRequest
	>({
		method: "PUT",
		url: getUsersControllerUpdateOwnProfileUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
