/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CategoriesControllerGetByIdPathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @example [object Object]
 */
export type CategoriesControllerGetById200 = any;

/**
 * @description Não autenticado
 */
export type CategoriesControllerGetById401 = any;

/**
 * @description Categoria não encontrada
 */
export type CategoriesControllerGetById404 = any;

export type CategoriesControllerGetByIdQueryResponse =
	CategoriesControllerGetById200;

export type CategoriesControllerGetByIdQuery = {
	Response: CategoriesControllerGetById200;
	PathParams: CategoriesControllerGetByIdPathParams;
	Errors: CategoriesControllerGetById401 | CategoriesControllerGetById404;
};
