/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CategoriesControllerRemovePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @example [object Object]
 */
export type CategoriesControllerRemove200 = any;

/**
 * @description Não autenticado
 */
export type CategoriesControllerRemove401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type CategoriesControllerRemove403 = any;

/**
 * @description Categoria não encontrada
 */
export type CategoriesControllerRemove404 = any;

/**
 * @description Categoria possui dependências
 */
export type CategoriesControllerRemove409 = any;

export type CategoriesControllerRemoveMutationResponse =
	CategoriesControllerRemove200;

export type CategoriesControllerRemoveMutation = {
	Response: CategoriesControllerRemove200;
	PathParams: CategoriesControllerRemovePathParams;
	Errors:
		| CategoriesControllerRemove401
		| CategoriesControllerRemove403
		| CategoriesControllerRemove404
		| CategoriesControllerRemove409;
};
