/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCategoryDto } from "../create-category-dto.ts";

/**
 * @description Categoria criada com sucesso
 */
export type CategoriesControllerCreate201 = any;

/**
 * @description Não autenticado
 */
export type CategoriesControllerCreate401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type CategoriesControllerCreate403 = any;

/**
 * @description Uma categoria com este nome já existe
 */
export type CategoriesControllerCreate409 = any;

export type CategoriesControllerCreateMutationRequest = CreateCategoryDto;

export type CategoriesControllerCreateMutationResponse =
	CategoriesControllerCreate201;

export type CategoriesControllerCreateMutation = {
	Response: CategoriesControllerCreate201;
	Request: CategoriesControllerCreateMutationRequest;
	Errors:
		| CategoriesControllerCreate401
		| CategoriesControllerCreate403
		| CategoriesControllerCreate409;
};
