/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateCategoryDto } from "../update-category-dto.ts";

export type CategoriesControllerUpdatePathParams = {
	/**
	 * @type string
	 */
	id: string;
};

/**
 * @description Categoria atualizada com sucesso
 */
export type CategoriesControllerUpdate200 = any;

/**
 * @description Não autenticado
 */
export type CategoriesControllerUpdate401 = any;

/**
 * @description Sem permissão para executar esta ação
 */
export type CategoriesControllerUpdate403 = any;

/**
 * @description Categoria não encontrada
 */
export type CategoriesControllerUpdate404 = any;

/**
 * @description Uma categoria com este nome já existe
 */
export type CategoriesControllerUpdate409 = any;

export type CategoriesControllerUpdateMutationRequest = UpdateCategoryDto;

export type CategoriesControllerUpdateMutationResponse =
	CategoriesControllerUpdate200;

export type CategoriesControllerUpdateMutation = {
	Response: CategoriesControllerUpdate200;
	Request: CategoriesControllerUpdateMutationRequest;
	PathParams: CategoriesControllerUpdatePathParams;
	Errors:
		| CategoriesControllerUpdate401
		| CategoriesControllerUpdate403
		| CategoriesControllerUpdate404
		| CategoriesControllerUpdate409;
};
