/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @example [object Object]
 */
export type CategoriesControllerList200 = any;

/**
 * @description Não autenticado
 */
export type CategoriesControllerList401 = any;

export type CategoriesControllerListQueryResponse = CategoriesControllerList200;

export type CategoriesControllerListQuery = {
	Response: CategoriesControllerList200;
	Errors: CategoriesControllerList401;
};
