/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerListQueryResponse,
	BudgetsControllerListQueryParams,
} from "../schemas/budgets/budgets-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerListUrl() {
	const res = { method: "GET", url: `/v1/budgets` as const };
	return res;
}

/**
 * {@link /v1/budgets}
 */
export async function budgetsControllerList(
	params?: BudgetsControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		BudgetsControllerListQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getBudgetsControllerListUrl().url.toString(),
		params,
		...requestConfig,
	});
	return res.data;
}
