/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerProgressQueryResponse,
	BudgetsControllerProgressPathParams,
} from "../schemas/budgets/budgets-controller-progress.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerProgressUrl(
	id: BudgetsControllerProgressPathParams["id"],
) {
	const res = { method: "GET", url: `/v1/budgets/${id}/progress` as const };
	return res;
}

/**
 * {@link /v1/budgets/:id/progress}
 */
export async function budgetsControllerProgress(
	id: BudgetsControllerProgressPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		BudgetsControllerProgressQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getBudgetsControllerProgressUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
