/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerRemoveMutationResponse,
	BudgetsControllerRemovePathParams,
} from "../schemas/budgets/budgets-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerRemoveUrl(
	id: BudgetsControllerRemovePathParams["id"],
) {
	const res = { method: "DELETE", url: `/v1/budgets/${id}` as const };
	return res;
}

/**
 * {@link /v1/budgets/:id}
 */
export async function budgetsControllerRemove(
	id: BudgetsControllerRemovePathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		BudgetsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "DELETE",
		url: getBudgetsControllerRemoveUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
