/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerReplicateMutationRequest,
	BudgetsControllerReplicateMutationResponse,
} from "../schemas/budgets/budgets-controller-replicate.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerReplicateUrl() {
	const res = { method: "PUT", url: `/v1/budgets` as const };
	return res;
}

/**
 * {@link /v1/budgets}
 */
export async function budgetsControllerReplicate(
	data: BudgetsControllerReplicateMutationRequest,
	config: Partial<RequestConfig<BudgetsControllerReplicateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		BudgetsControllerReplicateMutationResponse,
		ResponseErrorConfig<Error>,
		BudgetsControllerReplicateMutationRequest
	>({
		method: "PUT",
		url: getBudgetsControllerReplicateUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
