/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerUpdateMutationRequest,
	BudgetsControllerUpdateMutationResponse,
	BudgetsControllerUpdatePathParams,
} from "../schemas/budgets/budgets-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerUpdateUrl(
	id: BudgetsControllerUpdatePathParams["id"],
) {
	const res = { method: "PUT", url: `/v1/budgets/${id}` as const };
	return res;
}

/**
 * {@link /v1/budgets/:id}
 */
export async function budgetsControllerUpdate(
	id: BudgetsControllerUpdatePathParams["id"],
	data: BudgetsControllerUpdateMutationRequest,
	config: Partial<RequestConfig<BudgetsControllerUpdateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		BudgetsControllerUpdateMutationResponse,
		ResponseErrorConfig<Error>,
		BudgetsControllerUpdateMutationRequest
	>({
		method: "PUT",
		url: getBudgetsControllerUpdateUrl(id).url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
