/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerCreateMutationRequest,
	BudgetsControllerCreateMutationResponse,
	BudgetsControllerCreate404,
	BudgetsControllerCreate409,
} from "../schemas/budgets/budgets-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerCreateUrl() {
	const res = { method: "POST", url: `/v1/budgets` as const };
	return res;
}

/**
 * {@link /v1/budgets}
 */
export async function budgetsControllerCreate(
	data: BudgetsControllerCreateMutationRequest,
	config: Partial<RequestConfig<BudgetsControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const requestData = data;

	const res = await request<
		BudgetsControllerCreateMutationResponse,
		ResponseErrorConfig<
			BudgetsControllerCreate404 | BudgetsControllerCreate409
		>,
		BudgetsControllerCreateMutationRequest
	>({
		method: "POST",
		url: getBudgetsControllerCreateUrl().url.toString(),
		data: requestData,
		...requestConfig,
	});
	return res.data;
}
