/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
	BudgetsControllerGetByIdQueryResponse,
	BudgetsControllerGetByIdPathParams,
	BudgetsControllerGetById404,
} from "../schemas/budgets/budgets-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getBudgetsControllerGetByIdUrl(
	id: BudgetsControllerGetByIdPathParams["id"],
) {
	const res = { method: "GET", url: `/v1/budgets/${id}` as const };
	return res;
}

/**
 * {@link /v1/budgets/:id}
 */
export async function budgetsControllerGetById(
	id: BudgetsControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		BudgetsControllerGetByIdQueryResponse,
		ResponseErrorConfig<BudgetsControllerGetById404>,
		unknown
	>({
		method: "GET",
		url: getBudgetsControllerGetByIdUrl(id).url.toString(),
		...requestConfig,
	});
	return res.data;
}
