/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerCreateMutationRequest,
	BudgetsControllerCreateMutationResponse,
	BudgetsControllerCreate404,
	BudgetsControllerCreate409,
} from "../../schemas/budgets/budgets-controller-create.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { budgetsControllerCreate } from "../budgets-controller-create.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const budgetsControllerCreateMutationKey = () =>
	[{ url: "/v1/budgets" }] as const;

export type BudgetsControllerCreateMutationKey = ReturnType<
	typeof budgetsControllerCreateMutationKey
>;

export function useBudgetsControllerCreateMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<BudgetsControllerCreateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = budgetsControllerCreateMutationKey();
	return mutationOptions<
		BudgetsControllerCreateMutationResponse,
		ResponseErrorConfig<
			BudgetsControllerCreate404 | BudgetsControllerCreate409
		>,
		{ data: BudgetsControllerCreateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return budgetsControllerCreate(data, config);
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerCreate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerCreateMutationResponse,
			ResponseErrorConfig<
				BudgetsControllerCreate404 | BudgetsControllerCreate409
			>,
			{ data: BudgetsControllerCreateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<BudgetsControllerCreateMutationRequest>> & {
			client?: Client;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerCreateMutationKey();

	const baseOptions = useBudgetsControllerCreateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerCreateMutationResponse,
		ResponseErrorConfig<
			BudgetsControllerCreate404 | BudgetsControllerCreate409
		>,
		{ data: BudgetsControllerCreateMutationRequest },
		TContext
	>;

	return useMutation<
		BudgetsControllerCreateMutationResponse,
		ResponseErrorConfig<
			BudgetsControllerCreate404 | BudgetsControllerCreate409
		>,
		{ data: BudgetsControllerCreateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerCreateMutationResponse,
		ResponseErrorConfig<
			BudgetsControllerCreate404 | BudgetsControllerCreate409
		>,
		{ data: BudgetsControllerCreateMutationRequest },
		TContext
	>;
}
