/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerListQueryResponse,
	BudgetsControllerListQueryParams,
} from "../../schemas/budgets/budgets-controller-list.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { budgetsControllerList } from "../budgets-controller-list.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const budgetsControllerListSuspenseQueryKey = (
	params?: BudgetsControllerListQueryParams,
) => [{ url: "/v1/budgets" }, ...(params ? [params] : [])] as const;

export type BudgetsControllerListSuspenseQueryKey = ReturnType<
	typeof budgetsControllerListSuspenseQueryKey
>;

export function useBudgetsControllerListSuspenseQueryOptions(
	params?: BudgetsControllerListQueryParams,
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = budgetsControllerListSuspenseQueryKey(params);
	return queryOptions<
		BudgetsControllerListQueryResponse,
		ResponseErrorConfig<Error>,
		BudgetsControllerListQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return budgetsControllerList(params, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerListSuspense<
	TData = BudgetsControllerListQueryResponse,
	TQueryKey extends QueryKey = BudgetsControllerListSuspenseQueryKey,
>(
	params?: BudgetsControllerListQueryParams,
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				BudgetsControllerListQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? budgetsControllerListSuspenseQueryKey(params);

	const query = useSuspenseQuery(
		{
			...useBudgetsControllerListSuspenseQueryOptions(params, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
