/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerUpdateMutationRequest,
	BudgetsControllerUpdateMutationResponse,
	BudgetsControllerUpdatePathParams,
} from "../../schemas/budgets/budgets-controller-update.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { budgetsControllerUpdate } from "../budgets-controller-update.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const budgetsControllerUpdateMutationKey = () =>
	[{ url: "/v1/budgets/:id" }] as const;

export type BudgetsControllerUpdateMutationKey = ReturnType<
	typeof budgetsControllerUpdateMutationKey
>;

export function useBudgetsControllerUpdateMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<BudgetsControllerUpdateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = budgetsControllerUpdateMutationKey();
	return mutationOptions<
		BudgetsControllerUpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{
			id: BudgetsControllerUpdatePathParams["id"];
			data: BudgetsControllerUpdateMutationRequest;
		},
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return budgetsControllerUpdate(id, data, config);
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerUpdate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerUpdateMutationResponse,
			ResponseErrorConfig<Error>,
			{
				id: BudgetsControllerUpdatePathParams["id"];
				data: BudgetsControllerUpdateMutationRequest;
			},
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig<BudgetsControllerUpdateMutationRequest>> & {
			client?: Client;
		};
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerUpdateMutationKey();

	const baseOptions = useBudgetsControllerUpdateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerUpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{
			id: BudgetsControllerUpdatePathParams["id"];
			data: BudgetsControllerUpdateMutationRequest;
		},
		TContext
	>;

	return useMutation<
		BudgetsControllerUpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{
			id: BudgetsControllerUpdatePathParams["id"];
			data: BudgetsControllerUpdateMutationRequest;
		},
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerUpdateMutationResponse,
		ResponseErrorConfig<Error>,
		{
			id: BudgetsControllerUpdatePathParams["id"];
			data: BudgetsControllerUpdateMutationRequest;
		},
		TContext
	>;
}
