/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerReplicateMutationRequest,
	BudgetsControllerReplicateMutationResponse,
} from "../../schemas/budgets/budgets-controller-replicate.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { budgetsControllerReplicate } from "../budgets-controller-replicate.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const budgetsControllerReplicateMutationKey = () =>
	[{ url: "/v1/budgets" }] as const;

export type BudgetsControllerReplicateMutationKey = ReturnType<
	typeof budgetsControllerReplicateMutationKey
>;

export function useBudgetsControllerReplicateMutationOptions<
	TContext = unknown,
>(
	config: Partial<RequestConfig<BudgetsControllerReplicateMutationRequest>> & {
		client?: Client;
	} = {},
) {
	const mutationKey = budgetsControllerReplicateMutationKey();
	return mutationOptions<
		BudgetsControllerReplicateMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: BudgetsControllerReplicateMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ data }) => {
			return budgetsControllerReplicate(data, config);
		},
	});
}

/**
 * {@link /v1/budgets}
 */
export function useBudgetsControllerReplicate<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerReplicateMutationResponse,
			ResponseErrorConfig<Error>,
			{ data: BudgetsControllerReplicateMutationRequest },
			TContext
		> & { client?: QueryClient };
		client?: Partial<
			RequestConfig<BudgetsControllerReplicateMutationRequest>
		> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerReplicateMutationKey();

	const baseOptions = useBudgetsControllerReplicateMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerReplicateMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: BudgetsControllerReplicateMutationRequest },
		TContext
	>;

	return useMutation<
		BudgetsControllerReplicateMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: BudgetsControllerReplicateMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerReplicateMutationResponse,
		ResponseErrorConfig<Error>,
		{ data: BudgetsControllerReplicateMutationRequest },
		TContext
	>;
}
