/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerGetByIdQueryResponse,
	BudgetsControllerGetByIdPathParams,
	BudgetsControllerGetById404,
} from "../../schemas/budgets/budgets-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { budgetsControllerGetById } from "../budgets-controller-get-by-id.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const budgetsControllerGetByIdSuspenseQueryKey = (
	id: BudgetsControllerGetByIdPathParams["id"],
) => [{ url: "/v1/budgets/:id", params: { id: id } }] as const;

export type BudgetsControllerGetByIdSuspenseQueryKey = ReturnType<
	typeof budgetsControllerGetByIdSuspenseQueryKey
>;

export function useBudgetsControllerGetByIdSuspenseQueryOptions(
	id: BudgetsControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = budgetsControllerGetByIdSuspenseQueryKey(id);
	return queryOptions<
		BudgetsControllerGetByIdQueryResponse,
		ResponseErrorConfig<BudgetsControllerGetById404>,
		BudgetsControllerGetByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return budgetsControllerGetById(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerGetByIdSuspense<
	TData = BudgetsControllerGetByIdQueryResponse,
	TQueryKey extends QueryKey = BudgetsControllerGetByIdSuspenseQueryKey,
>(
	id: BudgetsControllerGetByIdPathParams["id"],
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				BudgetsControllerGetByIdQueryResponse,
				ResponseErrorConfig<BudgetsControllerGetById404>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? budgetsControllerGetByIdSuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{
			...useBudgetsControllerGetByIdSuspenseQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<
		TData,
		ResponseErrorConfig<BudgetsControllerGetById404>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
