/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerGetByIdQueryResponse,
	BudgetsControllerGetByIdPathParams,
	BudgetsControllerGetById404,
} from "../../schemas/budgets/budgets-controller-get-by-id.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { budgetsControllerGetById } from "../budgets-controller-get-by-id.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const budgetsControllerGetByIdQueryKey = (
	id: BudgetsControllerGetByIdPathParams["id"],
) => [{ url: "/v1/budgets/:id", params: { id: id } }] as const;

export type BudgetsControllerGetByIdQueryKey = ReturnType<
	typeof budgetsControllerGetByIdQueryKey
>;

export function useBudgetsControllerGetByIdQueryOptions(
	id: BudgetsControllerGetByIdPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = budgetsControllerGetByIdQueryKey(id);
	return queryOptions<
		BudgetsControllerGetByIdQueryResponse,
		ResponseErrorConfig<BudgetsControllerGetById404>,
		BudgetsControllerGetByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return budgetsControllerGetById(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerGetById<
	TData = BudgetsControllerGetByIdQueryResponse,
	TQueryData = BudgetsControllerGetByIdQueryResponse,
	TQueryKey extends QueryKey = BudgetsControllerGetByIdQueryKey,
>(
	id: BudgetsControllerGetByIdPathParams["id"],
	options: {
		query?: Partial<
			QueryObserverOptions<
				BudgetsControllerGetByIdQueryResponse,
				ResponseErrorConfig<BudgetsControllerGetById404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? budgetsControllerGetByIdQueryKey(id);

	const query = useQuery(
		{
			...useBudgetsControllerGetByIdQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<
		TData,
		ResponseErrorConfig<BudgetsControllerGetById404>
	> & { queryKey: TQueryKey };

	query.queryKey = queryKey as TQueryKey;

	return query;
}
