/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerRemoveMutationResponse,
	BudgetsControllerRemovePathParams,
} from "../../schemas/budgets/budgets-controller-remove.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	UseMutationOptions,
	UseMutationResult,
	QueryClient,
} from "@tanstack/react-query";
import { budgetsControllerRemove } from "../budgets-controller-remove.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const budgetsControllerRemoveMutationKey = () =>
	[{ url: "/v1/budgets/:id" }] as const;

export type BudgetsControllerRemoveMutationKey = ReturnType<
	typeof budgetsControllerRemoveMutationKey
>;

export function useBudgetsControllerRemoveMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const mutationKey = budgetsControllerRemoveMutationKey();
	return mutationOptions<
		BudgetsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: BudgetsControllerRemovePathParams["id"] },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id }) => {
			return budgetsControllerRemove(id, config);
		},
	});
}

/**
 * {@link /v1/budgets/:id}
 */
export function useBudgetsControllerRemove<TContext>(
	options: {
		mutation?: UseMutationOptions<
			BudgetsControllerRemoveMutationResponse,
			ResponseErrorConfig<Error>,
			{ id: BudgetsControllerRemovePathParams["id"] },
			TContext
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...mutationOptions } = mutation;
	const mutationKey =
		mutationOptions.mutationKey ?? budgetsControllerRemoveMutationKey();

	const baseOptions = useBudgetsControllerRemoveMutationOptions(
		config,
	) as UseMutationOptions<
		BudgetsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: BudgetsControllerRemovePathParams["id"] },
		TContext
	>;

	return useMutation<
		BudgetsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: BudgetsControllerRemovePathParams["id"] },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		BudgetsControllerRemoveMutationResponse,
		ResponseErrorConfig<Error>,
		{ id: BudgetsControllerRemovePathParams["id"] },
		TContext
	>;
}
