/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
	BudgetsControllerProgressQueryResponse,
	BudgetsControllerProgressPathParams,
} from "../../schemas/budgets/budgets-controller-progress.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { budgetsControllerProgress } from "../budgets-controller-progress.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const budgetsControllerProgressSuspenseQueryKey = (
	id: BudgetsControllerProgressPathParams["id"],
) => [{ url: "/v1/budgets/:id/progress", params: { id: id } }] as const;

export type BudgetsControllerProgressSuspenseQueryKey = ReturnType<
	typeof budgetsControllerProgressSuspenseQueryKey
>;

export function useBudgetsControllerProgressSuspenseQueryOptions(
	id: BudgetsControllerProgressPathParams["id"],
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = budgetsControllerProgressSuspenseQueryKey(id);
	return queryOptions<
		BudgetsControllerProgressQueryResponse,
		ResponseErrorConfig<Error>,
		BudgetsControllerProgressQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return budgetsControllerProgress(id, {
				...config,
				signal: config.signal ?? signal,
			});
		},
	});
}

/**
 * {@link /v1/budgets/:id/progress}
 */
export function useBudgetsControllerProgressSuspense<
	TData = BudgetsControllerProgressQueryResponse,
	TQueryKey extends QueryKey = BudgetsControllerProgressSuspenseQueryKey,
>(
	id: BudgetsControllerProgressPathParams["id"],
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				BudgetsControllerProgressQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient };
		client?: Partial<RequestConfig> & { client?: Client };
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {};
	const { client: queryClient, ...resolvedOptions } = queryConfig;
	const queryKey =
		resolvedOptions?.queryKey ?? budgetsControllerProgressSuspenseQueryKey(id);

	const query = useSuspenseQuery(
		{
			...useBudgetsControllerProgressSuspenseQueryOptions(id, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
		queryKey: TQueryKey;
	};

	query.queryKey = queryKey as TQueryKey;

	return query;
}
