/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createCategoryDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type CreateCategoryDtoTypeEnumKey =
	(typeof createCategoryDtoTypeEnum)[keyof typeof createCategoryDtoTypeEnum];

export type CreateCategoryDto = {
	/**
	 * @type string
	 */
	name: string;
	/**
	 * @type string
	 */
	color: string;
	/**
	 * @type string | undefined
	 */
	icon?: string;
	/**
	 * @type string | undefined
	 */
	type?: CreateCategoryDtoTypeEnumKey;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	isDefault?: boolean;
};
