/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ResetPasswordDto = {
	/**
	 * @type string
	 */
	token: string;
	/**
	 * @type string
	 */
	password: string;
};
