/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateCategoryDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
	AMBOS: "AMBOS",
} as const;

export type UpdateCategoryDtoTypeEnumKey =
	(typeof updateCategoryDtoTypeEnum)[keyof typeof updateCategoryDtoTypeEnum];

export type UpdateCategoryDto = {
	/**
	 * @type string | undefined
	 */
	name?: string;
	/**
	 * @type string | undefined
	 */
	color?: string;
	/**
	 * @type string | undefined
	 */
	icon?: string;
	/**
	 * @type string | undefined
	 */
	type?: UpdateCategoryDtoTypeEnumKey;
	/**
	 * @default false
	 * @type boolean | undefined
	 */
	isDefault?: boolean;
};
