/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateTransactionDtoTypeEnum = {
	GANHO: "GANHO",
	GASTO: "GASTO",
} as const;

export type UpdateTransactionDtoTypeEnumKey =
	(typeof updateTransactionDtoTypeEnum)[keyof typeof updateTransactionDtoTypeEnum];

export const updateTransactionDtoTagEnum = {
	FALTA: "FALTA",
	PAGO: "PAGO",
	DEVOLVER: "DEVOLVER",
	ECONOMIA: "ECONOMIA",
} as const;

export type UpdateTransactionDtoTagEnumKey =
	(typeof updateTransactionDtoTagEnum)[keyof typeof updateTransactionDtoTagEnum];

export const updateTransactionDtoPaymentMethodEnum = {
	PIX: "PIX",
	DEBITO: "DEBITO",
	CREDITO: "CREDITO",
} as const;

export type UpdateTransactionDtoPaymentMethodEnumKey =
	(typeof updateTransactionDtoPaymentMethodEnum)[keyof typeof updateTransactionDtoPaymentMethodEnum];

export type UpdateTransactionDto = {
	/**
	 * @type string | undefined
	 */
	description?: string;
	/**
	 * @type number | undefined
	 */
	amount?: number;
	/**
	 * @type string | undefined
	 */
	date?: string;
	/**
	 * @type string | undefined
	 */
	type?: UpdateTransactionDtoTypeEnumKey;
	/**
	 * @type string | undefined
	 */
	categoryId?: string;
	/**
	 * @type string | undefined
	 */
	notes?: string;
	/**
	 * @type string
	 */
	tag?: UpdateTransactionDtoTagEnumKey | null;
	/**
	 * @type string
	 */
	paymentMethod?: UpdateTransactionDtoPaymentMethodEnumKey | null;
	/**
	 * @minLength 2
	 * @maxLength 12
	 * @type number | undefined
	 */
	installmentCount?: number;
};
