/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { AppControllerGetHealthQueryResponse } from "../schemas/health/app-controller-get-health.ts";
import type {
	Client,
	RequestConfig,
	ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function getAppControllerGetHealthUrl() {
	const res = { method: "GET", url: `/v1` as const };
	return res;
}

/**
 * {@link /v1}
 */
export async function appControllerGetHealth(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config;

	const res = await request<
		AppControllerGetHealthQueryResponse,
		ResponseErrorConfig<Error>,
		unknown
	>({
		method: "GET",
		url: getAppControllerGetHealthUrl().url.toString(),
		...requestConfig,
	});
	return res.data;
}
